Repository atlp-rwanda/orcas-phantom-frontend, pull requests merged in 2020-09, with the labels that each got.

#1 chore: Setup Testing Environment
  .babelrc
  __mocks__/fileMock.js
  babel.config.js
  package-lock.json
  package.json
  src/__test__/index.test.js
  src/index.js
Labels: Ready to be merged

#2 React setup
  .babelrc
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  src/components/About.js
  src/components/Nav.js
  src/components/app.js
  src/css/app.css
  src/index.html
  src/index.js
  webpack.config.js
Labels: Fixing issues, Request reviews

#5 fixed heroku deployement import errors
  package-lock.json
  package.json
  server.js
  webpack.config.js
Labels: Ready to be merged

#6 Set up Docker deployment
  .dockerignore
  .eslintrc.js
  .eslintrc.json
  Dockerfile
  __mocks__/fileMock.js
  babel.config.js
  docker-compose.yaml
  package-lock.json
  package.json
  server.js
  src/__test__/index.test.js
  src/components/About.js
  src/components/Nav.js
  src/components/app.css
  src/components/app.js
  src/css/app.css
  src/index.html
  src/index.js
  webpack.config.js
  yarn.lock
Labels: Request reviews
